import {
  escape as _escape,
  unescape as _unescape,
  camelCase,
  capitalize,
  constantCase,
  kebabCase,
  lowerCase,
  lowerFirst,
  pascalCase,
  snakeCase,
  startCase,
  trim,
  trimEnd,
  trimStart,
  upperCase,
  upperFirst,
  words,
} from 'es-toolkit';

export const stringUtilities = {
  camelCase: camelCase,
  capitalize: capitalize,
  constantCase: constantCase,
  escape: _escape,
  kebabCase: kebabCase,
  lowerCase: lowerCase,
  lowerFirst: lowerFirst,
  pascalCase: pascalCase,
  snakeCase: snakeCase,
  startCase: startCase,
  trim: trim,
  trimEnd: trimEnd,
  trimStart: trimStart,
  unescape: _unescape,
  upperCase: upperCase,
  upperFirst: upperFirst,
  words: words,
};
